service: meme-search-standard
image: neonwatty/meme-search-demo-one
servers:
  web:
    hosts:
      - 44.240.243.23

proxy:
  app_port: 8501
  ssl: true
  host: meme-search.standard.ytdatakit.xyz
  healthcheck:
    interval: 3
    path: /
    timeout: 10

registry:
  server: ghcr.io
  username: neonwatty
  password:
    - GITHUB_REGISTRY_TOKEN

# Configure builder setup.
builder:
  arch: amd64
  dockerfile: "./Dockerfile_standard"

# Use a different ssh user than root
ssh:
  user: ubuntu
