service: meme-search-pro
image: neonwatty/meme-search-demo-two
servers:
  web:
    hosts:
      - 44.240.243.23

proxy:
  app_port: 3000
  ssl: true
  host: meme-search.pro.ytdatakit.xyz
  healthcheck:
    interval: 3
    path: /
    timeout: 10

registry:
  server: ghcr.io
  username: neonwatty
  password:
    - GITHUB_REGISTRY_TOKEN

# Configure builder setup.
builder:
  arch: amd64
  dockerfile: "./Dockerfile_pro"

# Use a different ssh user than root
ssh:
  user: ubuntu

accessories:
  postgres:
    image: pgvector/pgvector:pg17
    host: 44.240.243.23
    directories:
      - ./meme_search_pro/db_data/meme-search-db:/var/lib/postgresql/data
    env:
      clear:
        POSTGRES_DB: meme_search
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
    port: "127.0.0.1:5432:5432"
