version: "3.8"

services:
  meme_search_pro:
    image: ghcr.io/neonwatty/meme_search_pro:latest
    container_name: meme_search_pro
    environment:
      - DATABASE_URL=postgres://postgres:postgres@meme-search-db:5432/meme_search
    ports:
      - "3000:3000"
    depends_on:
      meme_search_db:
        condition: service_healthy
    volumes: # <-- any additional meme directory must be mounted here
      - ./meme_search_pro/memes/:/rails/public/memes # <-- example meme directories

  meme_search_db:
    image: pgvector/pgvector:pg17
    container_name: meme-search-db # note: must use - and not _ as ActiveRecord uses URI::RFC2396_Parser to parse database URLs
    volumes:
      - ./meme_search_pro/db_data/meme-search-db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: meme_search
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
